package com.ctbri.dao;

import com.ctbri.vo.CsAlarmhuawei;

public interface CsAlarmhuaweiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_alarmhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_alarmhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsAlarmhuawei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_alarmhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsAlarmhuawei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_alarmhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsAlarmhuawei selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_alarmhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsAlarmhuawei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_alarmhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsAlarmhuawei record);
}