package com.ctbri.dao;

import com.ctbri.vo.CsAuthority;

public interface CsAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsAuthority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsAuthority record);
}