package com.ctbri.dao;

import com.ctbri.vo.CsDistrict;

public interface CsDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_district
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_district
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_district
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_district
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsDistrict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_district
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_district
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsDistrict record);
}