package com.ctbri.dao;

import com.ctbri.vo.CsLinkman;

public interface CsLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_linkman
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_linkman
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_linkman
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_linkman
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsLinkman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_linkman
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_linkman
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsLinkman record);
}