package com.ctbri.dao;

import com.ctbri.vo.CsOrderIp;

public interface CsOrderIpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_order_ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_order_ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsOrderIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_order_ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsOrderIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_order_ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsOrderIp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_order_ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsOrderIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_order_ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsOrderIp record);
}