package com.ctbri.dao;

import com.ctbri.vo.CsTaskhuawei;

public interface CsTaskhuaweiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_taskhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_taskhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsTaskhuawei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_taskhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsTaskhuawei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_taskhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsTaskhuawei selectByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_taskhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsTaskhuawei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_taskhuawei
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsTaskhuawei record);
}