package com.ctbri.dao;

import com.ctbri.vo.CsTask;

public interface CsTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_task
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_task
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_task
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_task
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsTask selectByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_task
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_task
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsTask record);
}