package com.ctbri.dao;

import com.ctbri.vo.CsAuthorityUsertype;

public interface CsAuthorityUsertypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority_usertype
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsAuthorityUsertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_authority_usertype
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsAuthorityUsertype record);
}