package com.ctbri.dao;

import com.ctbri.vo.CsEnginecfg;

public interface CsEnginecfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_enginecfg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_enginecfg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsEnginecfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_enginecfg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsEnginecfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_enginecfg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsEnginecfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_enginecfg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsEnginecfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_enginecfg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsEnginecfg record);
}