package com.ctbri.dao;

import com.ctbri.vo.CsFactory;

public interface CsFactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsFactory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsFactory record);
}