package com.ctbri.dao;

import com.ctbri.vo.CsMobile;

public interface CsMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(String mobilenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsMobile selectByPrimaryKey(String mobilenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsMobile record);
}