package com.ctbri.dao;

import com.ctbri.vo.CsNotice;

public interface CsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_notice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_notice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insert(CsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_notice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int insertSelective(CsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_notice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    CsNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_notice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKeySelective(CsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_notice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    int updateByPrimaryKey(CsNotice record);
}