package com.ctbri.vo;

import java.util.Date;

public class CsAlarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.alarm_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date alarmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.score
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.level
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.advice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String advice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.alarm_content
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String alarmContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.keyword
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.alarm_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String alarmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarm.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer districtid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.id
     *
     * @return the value of cs_alarm.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.id
     *
     * @param id the value for cs_alarm.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.name
     *
     * @return the value of cs_alarm.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.name
     *
     * @param name the value for cs_alarm.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.alarm_time
     *
     * @return the value of cs_alarm.alarm_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getAlarmTime() {
        return alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.alarm_time
     *
     * @param alarmTime the value for cs_alarm.alarm_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAlarmTime(Date alarmTime) {
        this.alarmTime = alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.score
     *
     * @return the value of cs_alarm.score
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.score
     *
     * @param score the value for cs_alarm.score
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.level
     *
     * @return the value of cs_alarm.level
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.level
     *
     * @param level the value for cs_alarm.level
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.advice
     *
     * @return the value of cs_alarm.advice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.advice
     *
     * @param advice the value for cs_alarm.advice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.alarm_content
     *
     * @return the value of cs_alarm.alarm_content
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAlarmContent() {
        return alarmContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.alarm_content
     *
     * @param alarmContent the value for cs_alarm.alarm_content
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAlarmContent(String alarmContent) {
        this.alarmContent = alarmContent == null ? null : alarmContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.url
     *
     * @return the value of cs_alarm.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.url
     *
     * @param url the value for cs_alarm.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.keyword
     *
     * @return the value of cs_alarm.keyword
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.keyword
     *
     * @param keyword the value for cs_alarm.keyword
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.taskId
     *
     * @return the value of cs_alarm.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.taskId
     *
     * @param taskid the value for cs_alarm.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.alarm_type
     *
     * @return the value of cs_alarm.alarm_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.alarm_type
     *
     * @param alarmType the value for cs_alarm.alarm_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType == null ? null : alarmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.userId
     *
     * @return the value of cs_alarm.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.userId
     *
     * @param userid the value for cs_alarm.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.group_id
     *
     * @return the value of cs_alarm.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.group_id
     *
     * @param groupId the value for cs_alarm.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.serviceId
     *
     * @return the value of cs_alarm.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.serviceId
     *
     * @param serviceid the value for cs_alarm.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarm.districtId
     *
     * @return the value of cs_alarm.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getDistrictid() {
        return districtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarm.districtId
     *
     * @param districtid the value for cs_alarm.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
}