package com.ctbri.vo;

public class CsAuthorityUsertype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_authority_usertype.userType
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_authority_usertype.authorityId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer authorityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_authority_usertype.userType
     *
     * @return the value of cs_authority_usertype.userType
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_authority_usertype.userType
     *
     * @param usertype the value for cs_authority_usertype.userType
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_authority_usertype.authorityId
     *
     * @return the value of cs_authority_usertype.authorityId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getAuthorityid() {
        return authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_authority_usertype.authorityId
     *
     * @param authorityid the value for cs_authority_usertype.authorityId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAuthorityid(Integer authorityid) {
        this.authorityid = authorityid;
    }
}