package com.ctbri.vo;

public class CsDistrict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.longitude
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.latitude
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.count1
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer count1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.count2
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer count2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.count3
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer count3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.count4
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer count4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_district.count5
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer count5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.id
     *
     * @return the value of cs_district.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.id
     *
     * @param id the value for cs_district.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.name
     *
     * @return the value of cs_district.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.name
     *
     * @param name the value for cs_district.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.longitude
     *
     * @return the value of cs_district.longitude
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.longitude
     *
     * @param longitude the value for cs_district.longitude
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.latitude
     *
     * @return the value of cs_district.latitude
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.latitude
     *
     * @param latitude the value for cs_district.latitude
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.count1
     *
     * @return the value of cs_district.count1
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getCount1() {
        return count1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.count1
     *
     * @param count1 the value for cs_district.count1
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCount1(Integer count1) {
        this.count1 = count1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.count2
     *
     * @return the value of cs_district.count2
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getCount2() {
        return count2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.count2
     *
     * @param count2 the value for cs_district.count2
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCount2(Integer count2) {
        this.count2 = count2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.count3
     *
     * @return the value of cs_district.count3
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getCount3() {
        return count3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.count3
     *
     * @param count3 the value for cs_district.count3
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCount3(Integer count3) {
        this.count3 = count3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.count4
     *
     * @return the value of cs_district.count4
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getCount4() {
        return count4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.count4
     *
     * @param count4 the value for cs_district.count4
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCount4(Integer count4) {
        this.count4 = count4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_district.count5
     *
     * @return the value of cs_district.count5
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getCount5() {
        return count5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_district.count5
     *
     * @param count5 the value for cs_district.count5
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCount5(Integer count5) {
        this.count5 = count5;
    }
}