package com.ctbri.vo;

public class CsLinkman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_linkman.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_linkman.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_linkman.mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_linkman.email
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_linkman.company
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_linkman.address
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_linkman.userid
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_linkman.id
     *
     * @return the value of cs_linkman.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_linkman.id
     *
     * @param id the value for cs_linkman.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_linkman.name
     *
     * @return the value of cs_linkman.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_linkman.name
     *
     * @param name the value for cs_linkman.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_linkman.mobile
     *
     * @return the value of cs_linkman.mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_linkman.mobile
     *
     * @param mobile the value for cs_linkman.mobile
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_linkman.email
     *
     * @return the value of cs_linkman.email
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_linkman.email
     *
     * @param email the value for cs_linkman.email
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_linkman.company
     *
     * @return the value of cs_linkman.company
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_linkman.company
     *
     * @param company the value for cs_linkman.company
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_linkman.address
     *
     * @return the value of cs_linkman.address
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_linkman.address
     *
     * @param address the value for cs_linkman.address
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_linkman.userid
     *
     * @return the value of cs_linkman.userid
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_linkman.userid
     *
     * @param userid the value for cs_linkman.userid
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}