package com.ctbri.vo;

public class CsMobile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_mobile.MobileNumber
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String mobilenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_mobile.Times
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_mobile.sendDate
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String senddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_mobile.MobileNumber
     *
     * @return the value of cs_mobile.MobileNumber
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getMobilenumber() {
        return mobilenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_mobile.MobileNumber
     *
     * @param mobilenumber the value for cs_mobile.MobileNumber
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber == null ? null : mobilenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_mobile.Times
     *
     * @return the value of cs_mobile.Times
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_mobile.Times
     *
     * @param times the value for cs_mobile.Times
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_mobile.sendDate
     *
     * @return the value of cs_mobile.sendDate
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getSenddate() {
        return senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_mobile.sendDate
     *
     * @param senddate the value for cs_mobile.sendDate
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setSenddate(String senddate) {
        this.senddate = senddate == null ? null : senddate.trim();
    }
}