package com.ctbri.vo;

import java.util.Date;

public class CsNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_notice.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_notice.noticeName
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String noticename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_notice.noticeDesc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String noticedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_notice.createDate
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_notice.Id
     *
     * @return the value of cs_notice.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_notice.Id
     *
     * @param id the value for cs_notice.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_notice.noticeName
     *
     * @return the value of cs_notice.noticeName
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getNoticename() {
        return noticename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_notice.noticeName
     *
     * @param noticename the value for cs_notice.noticeName
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setNoticename(String noticename) {
        this.noticename = noticename == null ? null : noticename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_notice.noticeDesc
     *
     * @return the value of cs_notice.noticeDesc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getNoticedesc() {
        return noticedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_notice.noticeDesc
     *
     * @param noticedesc the value for cs_notice.noticeDesc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setNoticedesc(String noticedesc) {
        this.noticedesc = noticedesc == null ? null : noticedesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_notice.createDate
     *
     * @return the value of cs_notice.createDate
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_notice.createDate
     *
     * @param createdate the value for cs_notice.createDate
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}