package com.ctbri.vo;

import java.util.Date;

public class CsOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.begin_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.end_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.create_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.task_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date taskDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.scan_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer scanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.contactId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer contactid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.message
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer websoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.id
     *
     * @return the value of cs_order.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.id
     *
     * @param id the value for cs_order.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.type
     *
     * @return the value of cs_order.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.type
     *
     * @param type the value for cs_order.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.begin_date
     *
     * @return the value of cs_order.begin_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.begin_date
     *
     * @param beginDate the value for cs_order.begin_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.end_date
     *
     * @return the value of cs_order.end_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.end_date
     *
     * @param endDate the value for cs_order.end_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.serviceId
     *
     * @return the value of cs_order.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.serviceId
     *
     * @param serviceid the value for cs_order.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.create_date
     *
     * @return the value of cs_order.create_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.create_date
     *
     * @param createDate the value for cs_order.create_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.task_date
     *
     * @return the value of cs_order.task_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getTaskDate() {
        return taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.task_date
     *
     * @param taskDate the value for cs_order.task_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTaskDate(Date taskDate) {
        this.taskDate = taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.scan_type
     *
     * @return the value of cs_order.scan_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getScanType() {
        return scanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.scan_type
     *
     * @param scanType the value for cs_order.scan_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setScanType(Integer scanType) {
        this.scanType = scanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.userId
     *
     * @return the value of cs_order.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.userId
     *
     * @param userid the value for cs_order.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.contactId
     *
     * @return the value of cs_order.contactId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getContactid() {
        return contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.contactId
     *
     * @param contactid the value for cs_order.contactId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setContactid(Integer contactid) {
        this.contactid = contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.remarks
     *
     * @return the value of cs_order.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.remarks
     *
     * @param remarks the value for cs_order.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.status
     *
     * @return the value of cs_order.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.status
     *
     * @param status the value for cs_order.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.message
     *
     * @return the value of cs_order.message
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.message
     *
     * @param message the value for cs_order.message
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setMessage(Integer message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order.websoc
     *
     * @return the value of cs_order.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getWebsoc() {
        return websoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order.websoc
     *
     * @param websoc the value for cs_order.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setWebsoc(Integer websoc) {
        this.websoc = websoc;
    }
}