package com.ctbri.vo;

public class CsService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String factory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.module_name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.ordertype
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.parentC
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer parentc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_service.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer websoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.id
     *
     * @return the value of cs_service.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.id
     *
     * @param id the value for cs_service.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.name
     *
     * @return the value of cs_service.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.name
     *
     * @param name the value for cs_service.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.factory
     *
     * @return the value of cs_service.factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.factory
     *
     * @param factory the value for cs_service.factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.module_name
     *
     * @return the value of cs_service.module_name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.module_name
     *
     * @param moduleName the value for cs_service.module_name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.type
     *
     * @return the value of cs_service.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.type
     *
     * @param type the value for cs_service.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.status
     *
     * @return the value of cs_service.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.status
     *
     * @param status the value for cs_service.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.remarks
     *
     * @return the value of cs_service.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.remarks
     *
     * @param remarks the value for cs_service.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.ordertype
     *
     * @return the value of cs_service.ordertype
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.ordertype
     *
     * @param ordertype the value for cs_service.ordertype
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.parentC
     *
     * @return the value of cs_service.parentC
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getParentc() {
        return parentc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.parentC
     *
     * @param parentc the value for cs_service.parentC
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setParentc(Integer parentc) {
        this.parentc = parentc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_service.websoc
     *
     * @return the value of cs_service.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getWebsoc() {
        return websoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_service.websoc
     *
     * @param websoc the value for cs_service.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setWebsoc(Integer websoc) {
        this.websoc = websoc;
    }
}