package com.ctbri.vo;

import java.util.Date;

public class CsAlarmhuawei {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.attack_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String attackType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.start_time_attack
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date startTimeAttack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.attacker
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String attacker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.duration
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.attack_flow
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String attackFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.start_time_alert
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date startTimeAlert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_alarmhuawei.orderId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.id
     *
     * @return the value of cs_alarmhuawei.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.id
     *
     * @param id the value for cs_alarmhuawei.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.attack_type
     *
     * @return the value of cs_alarmhuawei.attack_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAttackType() {
        return attackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.attack_type
     *
     * @param attackType the value for cs_alarmhuawei.attack_type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAttackType(String attackType) {
        this.attackType = attackType == null ? null : attackType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.start_time_attack
     *
     * @return the value of cs_alarmhuawei.start_time_attack
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getStartTimeAttack() {
        return startTimeAttack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.start_time_attack
     *
     * @param startTimeAttack the value for cs_alarmhuawei.start_time_attack
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setStartTimeAttack(Date startTimeAttack) {
        this.startTimeAttack = startTimeAttack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.attacker
     *
     * @return the value of cs_alarmhuawei.attacker
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAttacker() {
        return attacker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.attacker
     *
     * @param attacker the value for cs_alarmhuawei.attacker
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAttacker(String attacker) {
        this.attacker = attacker == null ? null : attacker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.duration
     *
     * @return the value of cs_alarmhuawei.duration
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.duration
     *
     * @param duration the value for cs_alarmhuawei.duration
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.attack_flow
     *
     * @return the value of cs_alarmhuawei.attack_flow
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAttackFlow() {
        return attackFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.attack_flow
     *
     * @param attackFlow the value for cs_alarmhuawei.attack_flow
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAttackFlow(String attackFlow) {
        this.attackFlow = attackFlow == null ? null : attackFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.end_time
     *
     * @return the value of cs_alarmhuawei.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.end_time
     *
     * @param endTime the value for cs_alarmhuawei.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.start_time_alert
     *
     * @return the value of cs_alarmhuawei.start_time_alert
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getStartTimeAlert() {
        return startTimeAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.start_time_alert
     *
     * @param startTimeAlert the value for cs_alarmhuawei.start_time_alert
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setStartTimeAlert(Date startTimeAlert) {
        this.startTimeAlert = startTimeAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.taskId
     *
     * @return the value of cs_alarmhuawei.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.taskId
     *
     * @param taskid the value for cs_alarmhuawei.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.userId
     *
     * @return the value of cs_alarmhuawei.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.userId
     *
     * @param userid the value for cs_alarmhuawei.userId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_alarmhuawei.orderId
     *
     * @return the value of cs_alarmhuawei.orderId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_alarmhuawei.orderId
     *
     * @param orderid the value for cs_alarmhuawei.orderId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }
}