package com.ctbri.vo;

import java.util.Date;

public class CsAsset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.addr
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.userid
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.create_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_asset.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer districtId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.id
     *
     * @return the value of cs_asset.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.id
     *
     * @param id the value for cs_asset.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.name
     *
     * @return the value of cs_asset.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.name
     *
     * @param name the value for cs_asset.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.type
     *
     * @return the value of cs_asset.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.type
     *
     * @param type the value for cs_asset.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.addr
     *
     * @return the value of cs_asset.addr
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.addr
     *
     * @param addr the value for cs_asset.addr
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.status
     *
     * @return the value of cs_asset.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.status
     *
     * @param status the value for cs_asset.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.userid
     *
     * @return the value of cs_asset.userid
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.userid
     *
     * @param userid the value for cs_asset.userid
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.create_date
     *
     * @return the value of cs_asset.create_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.create_date
     *
     * @param createDate the value for cs_asset.create_date
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.remarks
     *
     * @return the value of cs_asset.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.remarks
     *
     * @param remarks the value for cs_asset.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.ip
     *
     * @return the value of cs_asset.ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.ip
     *
     * @param ip the value for cs_asset.ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_asset.districtId
     *
     * @return the value of cs_asset.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_asset.districtId
     *
     * @param districtid the value for cs_asset.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }
}