package com.ctbri.vo;

public class CsAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_authority.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_authority.authorityName
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String authorityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_authority.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_authority.state
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_authority.remark
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_authority.id
     *
     * @return the value of cs_authority.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_authority.id
     *
     * @param id the value for cs_authority.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_authority.authorityName
     *
     * @return the value of cs_authority.authorityName
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAuthorityname() {
        return authorityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_authority.authorityName
     *
     * @param authorityname the value for cs_authority.authorityName
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAuthorityname(String authorityname) {
        this.authorityname = authorityname == null ? null : authorityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_authority.url
     *
     * @return the value of cs_authority.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_authority.url
     *
     * @param url the value for cs_authority.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_authority.state
     *
     * @return the value of cs_authority.state
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_authority.state
     *
     * @param state the value for cs_authority.state
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_authority.remark
     *
     * @return the value of cs_authority.remark
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_authority.remark
     *
     * @param remark the value for cs_authority.remark
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}