package com.ctbri.vo;

public class CsEnginecfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.engine_number
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String engineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.engine_name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String engineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.equipment_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String equipmentFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.engine_addr
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String engineAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.engine_api
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String engineApi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.username
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.password
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.engine_capacity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String engineCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.engine_capacity_model
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String engineCapacityModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.maxTask
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer maxtask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enginecfg.activity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer activity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.Id
     *
     * @return the value of cs_enginecfg.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.Id
     *
     * @param id the value for cs_enginecfg.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.engine_number
     *
     * @return the value of cs_enginecfg.engine_number
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEngineNumber() {
        return engineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.engine_number
     *
     * @param engineNumber the value for cs_enginecfg.engine_number
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngineNumber(String engineNumber) {
        this.engineNumber = engineNumber == null ? null : engineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.engine_name
     *
     * @return the value of cs_enginecfg.engine_name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEngineName() {
        return engineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.engine_name
     *
     * @param engineName the value for cs_enginecfg.engine_name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngineName(String engineName) {
        this.engineName = engineName == null ? null : engineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.equipment_factory
     *
     * @return the value of cs_enginecfg.equipment_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEquipmentFactory() {
        return equipmentFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.equipment_factory
     *
     * @param equipmentFactory the value for cs_enginecfg.equipment_factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEquipmentFactory(String equipmentFactory) {
        this.equipmentFactory = equipmentFactory == null ? null : equipmentFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.engine_addr
     *
     * @return the value of cs_enginecfg.engine_addr
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEngineAddr() {
        return engineAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.engine_addr
     *
     * @param engineAddr the value for cs_enginecfg.engine_addr
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngineAddr(String engineAddr) {
        this.engineAddr = engineAddr == null ? null : engineAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.engine_api
     *
     * @return the value of cs_enginecfg.engine_api
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEngineApi() {
        return engineApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.engine_api
     *
     * @param engineApi the value for cs_enginecfg.engine_api
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngineApi(String engineApi) {
        this.engineApi = engineApi == null ? null : engineApi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.username
     *
     * @return the value of cs_enginecfg.username
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.username
     *
     * @param username the value for cs_enginecfg.username
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.password
     *
     * @return the value of cs_enginecfg.password
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.password
     *
     * @param password the value for cs_enginecfg.password
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.engine_capacity
     *
     * @return the value of cs_enginecfg.engine_capacity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEngineCapacity() {
        return engineCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.engine_capacity
     *
     * @param engineCapacity the value for cs_enginecfg.engine_capacity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngineCapacity(String engineCapacity) {
        this.engineCapacity = engineCapacity == null ? null : engineCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.engine_capacity_model
     *
     * @return the value of cs_enginecfg.engine_capacity_model
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEngineCapacityModel() {
        return engineCapacityModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.engine_capacity_model
     *
     * @param engineCapacityModel the value for cs_enginecfg.engine_capacity_model
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngineCapacityModel(String engineCapacityModel) {
        this.engineCapacityModel = engineCapacityModel == null ? null : engineCapacityModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.maxTask
     *
     * @return the value of cs_enginecfg.maxTask
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getMaxtask() {
        return maxtask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.maxTask
     *
     * @param maxtask the value for cs_enginecfg.maxTask
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setMaxtask(Integer maxtask) {
        this.maxtask = maxtask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enginecfg.activity
     *
     * @return the value of cs_enginecfg.activity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enginecfg.activity
     *
     * @param activity the value for cs_enginecfg.activity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setActivity(Integer activity) {
        this.activity = activity;
    }
}