package com.ctbri.vo;

public class CsFactory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_factory.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_factory.factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String factory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_factory.id
     *
     * @return the value of cs_factory.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_factory.id
     *
     * @param id the value for cs_factory.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_factory.factory
     *
     * @return the value of cs_factory.factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_factory.factory
     *
     * @param factory the value for cs_factory.factory
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }
}