package com.ctbri.vo;

public class CsLeakinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_leakinfo.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_leakinfo.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_leakinfo.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_leakinfo.desc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_leakinfo.test_method
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String testMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_leakinfo.advice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String advice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_leakinfo.Id
     *
     * @return the value of cs_leakinfo.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_leakinfo.Id
     *
     * @param id the value for cs_leakinfo.Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_leakinfo.type
     *
     * @return the value of cs_leakinfo.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_leakinfo.type
     *
     * @param type the value for cs_leakinfo.type
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_leakinfo.name
     *
     * @return the value of cs_leakinfo.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_leakinfo.name
     *
     * @param name the value for cs_leakinfo.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_leakinfo.desc
     *
     * @return the value of cs_leakinfo.desc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_leakinfo.desc
     *
     * @param desc the value for cs_leakinfo.desc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_leakinfo.test_method
     *
     * @return the value of cs_leakinfo.test_method
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getTestMethod() {
        return testMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_leakinfo.test_method
     *
     * @param testMethod the value for cs_leakinfo.test_method
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTestMethod(String testMethod) {
        this.testMethod = testMethod == null ? null : testMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_leakinfo.advice
     *
     * @return the value of cs_leakinfo.advice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_leakinfo.advice
     *
     * @param advice the value for cs_leakinfo.advice
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }
}