package com.ctbri.vo;

public class CsOrderIp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order_ip.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order_ip.orderId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order_ip.ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order_ip.bandwidth
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Boolean bandwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_order_ip.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Boolean serviceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order_ip.id
     *
     * @return the value of cs_order_ip.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order_ip.id
     *
     * @param id the value for cs_order_ip.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order_ip.orderId
     *
     * @return the value of cs_order_ip.orderId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order_ip.orderId
     *
     * @param orderid the value for cs_order_ip.orderId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order_ip.ip
     *
     * @return the value of cs_order_ip.ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order_ip.ip
     *
     * @param ip the value for cs_order_ip.ip
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order_ip.bandwidth
     *
     * @return the value of cs_order_ip.bandwidth
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Boolean getBandwidth() {
        return bandwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order_ip.bandwidth
     *
     * @param bandwidth the value for cs_order_ip.bandwidth
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setBandwidth(Boolean bandwidth) {
        this.bandwidth = bandwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_order_ip.serviceId
     *
     * @return the value of cs_order_ip.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Boolean getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_order_ip.serviceId
     *
     * @param serviceid the value for cs_order_ip.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setServiceid(Boolean serviceid) {
        this.serviceid = serviceid;
    }
}