package com.ctbri.vo;

import java.util.Date;

public class CsTaskhuawei {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskhuawei.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskhuawei.order_ip_Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer orderIpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskhuawei.execute_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date executeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskhuawei.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskhuawei.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskhuawei.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskhuawei.drainage
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer drainage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskhuawei.taskId
     *
     * @return the value of cs_taskhuawei.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskhuawei.taskId
     *
     * @param taskid the value for cs_taskhuawei.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskhuawei.order_ip_Id
     *
     * @return the value of cs_taskhuawei.order_ip_Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getOrderIpId() {
        return orderIpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskhuawei.order_ip_Id
     *
     * @param orderIpId the value for cs_taskhuawei.order_ip_Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setOrderIpId(Integer orderIpId) {
        this.orderIpId = orderIpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskhuawei.execute_time
     *
     * @return the value of cs_taskhuawei.execute_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskhuawei.execute_time
     *
     * @param executeTime the value for cs_taskhuawei.execute_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskhuawei.status
     *
     * @return the value of cs_taskhuawei.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskhuawei.status
     *
     * @param status the value for cs_taskhuawei.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskhuawei.remarks
     *
     * @return the value of cs_taskhuawei.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskhuawei.remarks
     *
     * @param remarks the value for cs_taskhuawei.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskhuawei.end_time
     *
     * @return the value of cs_taskhuawei.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskhuawei.end_time
     *
     * @param endTime the value for cs_taskhuawei.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskhuawei.drainage
     *
     * @return the value of cs_taskhuawei.drainage
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getDrainage() {
        return drainage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskhuawei.drainage
     *
     * @param drainage the value for cs_taskhuawei.drainage
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setDrainage(Integer drainage) {
        this.drainage = drainage;
    }
}