package com.ctbri.vo;

import java.util.Date;

public class CsTaskwarn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.cat1
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String cat1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.cat2
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String cat2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.severity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.rule
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.ct
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer ct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.app_p
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String appP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.tran_p
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String tranP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.msg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.task_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.warn_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date warnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_taskwarn.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer districtid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.id
     *
     * @return the value of cs_taskwarn.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.id
     *
     * @param id the value for cs_taskwarn.id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.cat1
     *
     * @return the value of cs_taskwarn.cat1
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getCat1() {
        return cat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.cat1
     *
     * @param cat1 the value for cs_taskwarn.cat1
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCat1(String cat1) {
        this.cat1 = cat1 == null ? null : cat1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.cat2
     *
     * @return the value of cs_taskwarn.cat2
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getCat2() {
        return cat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.cat2
     *
     * @param cat2 the value for cs_taskwarn.cat2
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCat2(String cat2) {
        this.cat2 = cat2 == null ? null : cat2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.name
     *
     * @return the value of cs_taskwarn.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.name
     *
     * @param name the value for cs_taskwarn.name
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.severity
     *
     * @return the value of cs_taskwarn.severity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.severity
     *
     * @param severity the value for cs_taskwarn.severity
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.rule
     *
     * @return the value of cs_taskwarn.rule
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.rule
     *
     * @param rule the value for cs_taskwarn.rule
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.ct
     *
     * @return the value of cs_taskwarn.ct
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getCt() {
        return ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.ct
     *
     * @param ct the value for cs_taskwarn.ct
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCt(Integer ct) {
        this.ct = ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.app_p
     *
     * @return the value of cs_taskwarn.app_p
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAppP() {
        return appP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.app_p
     *
     * @param appP the value for cs_taskwarn.app_p
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAppP(String appP) {
        this.appP = appP == null ? null : appP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.tran_p
     *
     * @return the value of cs_taskwarn.tran_p
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getTranP() {
        return tranP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.tran_p
     *
     * @param tranP the value for cs_taskwarn.tran_p
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTranP(String tranP) {
        this.tranP = tranP == null ? null : tranP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.url
     *
     * @return the value of cs_taskwarn.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.url
     *
     * @param url the value for cs_taskwarn.url
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.msg
     *
     * @return the value of cs_taskwarn.msg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.msg
     *
     * @param msg the value for cs_taskwarn.msg
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.task_id
     *
     * @return the value of cs_taskwarn.task_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.task_id
     *
     * @param taskId the value for cs_taskwarn.task_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.warn_time
     *
     * @return the value of cs_taskwarn.warn_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getWarnTime() {
        return warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.warn_time
     *
     * @param warnTime the value for cs_taskwarn.warn_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setWarnTime(Date warnTime) {
        this.warnTime = warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.group_id
     *
     * @return the value of cs_taskwarn.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.group_id
     *
     * @param groupId the value for cs_taskwarn.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.serviceId
     *
     * @return the value of cs_taskwarn.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.serviceId
     *
     * @param serviceid the value for cs_taskwarn.serviceId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_taskwarn.districtId
     *
     * @return the value of cs_taskwarn.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getDistrictid() {
        return districtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_taskwarn.districtId
     *
     * @param districtid the value for cs_taskwarn.districtId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
}