package com.ctbri.vo;

import java.util.Date;

public class CsTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.order_asset_Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String orderAssetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.execute_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date executeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.group_flag
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date groupFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.engineIP
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String engineip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.taskProgress
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String taskprogress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.currentUrl
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String currenturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.begin_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.scanTime
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String scantime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.issueCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String issuecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.requestCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String requestcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.urlCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String urlcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.averResponse
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String averresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.averSendCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String aversendcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.sendBytes
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String sendbytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.receiveBytes
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String receivebytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer websoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_task.engine
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    private Integer engine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.taskId
     *
     * @return the value of cs_task.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.taskId
     *
     * @param taskid the value for cs_task.taskId
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.order_asset_Id
     *
     * @return the value of cs_task.order_asset_Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getOrderAssetId() {
        return orderAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.order_asset_Id
     *
     * @param orderAssetId the value for cs_task.order_asset_Id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setOrderAssetId(String orderAssetId) {
        this.orderAssetId = orderAssetId == null ? null : orderAssetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.execute_time
     *
     * @return the value of cs_task.execute_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.execute_time
     *
     * @param executeTime the value for cs_task.execute_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.status
     *
     * @return the value of cs_task.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.status
     *
     * @param status the value for cs_task.status
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.group_flag
     *
     * @return the value of cs_task.group_flag
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getGroupFlag() {
        return groupFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.group_flag
     *
     * @param groupFlag the value for cs_task.group_flag
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setGroupFlag(Date groupFlag) {
        this.groupFlag = groupFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.remarks
     *
     * @return the value of cs_task.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.remarks
     *
     * @param remarks the value for cs_task.remarks
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.engineIP
     *
     * @return the value of cs_task.engineIP
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getEngineip() {
        return engineip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.engineIP
     *
     * @param engineip the value for cs_task.engineIP
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngineip(String engineip) {
        this.engineip = engineip == null ? null : engineip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.taskProgress
     *
     * @return the value of cs_task.taskProgress
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getTaskprogress() {
        return taskprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.taskProgress
     *
     * @param taskprogress the value for cs_task.taskProgress
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setTaskprogress(String taskprogress) {
        this.taskprogress = taskprogress == null ? null : taskprogress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.currentUrl
     *
     * @return the value of cs_task.currentUrl
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getCurrenturl() {
        return currenturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.currentUrl
     *
     * @param currenturl the value for cs_task.currentUrl
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setCurrenturl(String currenturl) {
        this.currenturl = currenturl == null ? null : currenturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.begin_time
     *
     * @return the value of cs_task.begin_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.begin_time
     *
     * @param beginTime the value for cs_task.begin_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.end_time
     *
     * @return the value of cs_task.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.end_time
     *
     * @param endTime the value for cs_task.end_time
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.scanTime
     *
     * @return the value of cs_task.scanTime
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getScantime() {
        return scantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.scanTime
     *
     * @param scantime the value for cs_task.scanTime
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setScantime(String scantime) {
        this.scantime = scantime == null ? null : scantime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.issueCount
     *
     * @return the value of cs_task.issueCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getIssuecount() {
        return issuecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.issueCount
     *
     * @param issuecount the value for cs_task.issueCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setIssuecount(String issuecount) {
        this.issuecount = issuecount == null ? null : issuecount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.requestCount
     *
     * @return the value of cs_task.requestCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getRequestcount() {
        return requestcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.requestCount
     *
     * @param requestcount the value for cs_task.requestCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setRequestcount(String requestcount) {
        this.requestcount = requestcount == null ? null : requestcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.urlCount
     *
     * @return the value of cs_task.urlCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getUrlcount() {
        return urlcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.urlCount
     *
     * @param urlcount the value for cs_task.urlCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setUrlcount(String urlcount) {
        this.urlcount = urlcount == null ? null : urlcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.averResponse
     *
     * @return the value of cs_task.averResponse
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAverresponse() {
        return averresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.averResponse
     *
     * @param averresponse the value for cs_task.averResponse
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAverresponse(String averresponse) {
        this.averresponse = averresponse == null ? null : averresponse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.averSendCount
     *
     * @return the value of cs_task.averSendCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getAversendcount() {
        return aversendcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.averSendCount
     *
     * @param aversendcount the value for cs_task.averSendCount
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setAversendcount(String aversendcount) {
        this.aversendcount = aversendcount == null ? null : aversendcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.sendBytes
     *
     * @return the value of cs_task.sendBytes
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getSendbytes() {
        return sendbytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.sendBytes
     *
     * @param sendbytes the value for cs_task.sendBytes
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setSendbytes(String sendbytes) {
        this.sendbytes = sendbytes == null ? null : sendbytes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.receiveBytes
     *
     * @return the value of cs_task.receiveBytes
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getReceivebytes() {
        return receivebytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.receiveBytes
     *
     * @param receivebytes the value for cs_task.receiveBytes
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setReceivebytes(String receivebytes) {
        this.receivebytes = receivebytes == null ? null : receivebytes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.websoc
     *
     * @return the value of cs_task.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getWebsoc() {
        return websoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.websoc
     *
     * @param websoc the value for cs_task.websoc
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setWebsoc(Integer websoc) {
        this.websoc = websoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.group_id
     *
     * @return the value of cs_task.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.group_id
     *
     * @param groupId the value for cs_task.group_id
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_task.engine
     *
     * @return the value of cs_task.engine
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public Integer getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_task.engine
     *
     * @param engine the value for cs_task.engine
     *
     * @mbggenerated Thu Oct 22 09:40:42 CST 2015
     */
    public void setEngine(Integer engine) {
        this.engine = engine;
    }
}